apiVersion: v1
kind: Service
metadata:
  name: demo-app-service
  namespace: demo
  labels:
    app: demo-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: demo-app